### ISSUE TITLE
Trim silence

### ISSUE THREAD

**Issue by Mec-iS** [Starchild-Music/explorative-models#5]
Song segmentation may be affected by the presence of silence at the beginning of the song. Use librosa to pre-process all the tracks:
```
# Load some audio
y, sr = librosa.load(librosa.ex('choice'))
# Trim the beginning and ending silence
yt, index = librosa.effects.trim(y)
# Print the durations
print(librosa.get_duration(y), librosa.get_duration(yt))
25.025986394557822 25.007891156462584
```

**Comment by Mec-iS** [comment]
current tracks are already trimmed but we cannot assume all will be in the future

**Comment by Fenchpress** [comment]
they all are not trimmed.  could try marking beat locations by first identifying beat 1 of highest confidence a measure.
