### ISSUE TITLE
[Tooling]Segments listening and visualization (with gradio)

### ISSUE THREAD

**Issue by Mec-iS** [Starchild-Music/explorative-models#7]
We should provide QA with a way of loading the results of segmentation into a notebook so to listen and visualize spectra.

Inputs:
* Song Name
* Segment label: "A1", "B2", ...
* OR in alternative: start and end of the segment in seconds (to listen to arbitrary segments)

Outputs:
* A display of the resulting segments as loaded from a JAMS file 
* A player to listen to the segment
* a visualization of waveform, chroma, Mel-spectrogram

**Comment by jghuynh** [comment]
#6

**Comment by Mec-iS** [comment]
#14
